#!/usr/bin/env python3
"""Sync chapter README files into docs/chapters/ for MkDocs."""

from __future__ import annotations

import re
import shutil
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / "docs" / "concept_index.yaml"
OUT_DIR = ROOT / "docs" / "chapters"
NAV_OUT = ROOT / "docs" / "_nav_chapters.yaml"
ASSETS_SRC = ROOT / "assets" / "animations"
ASSETS_DST = ROOT / "docs" / "assets" / "animations"


def _rewrite_links(text: str) -> str:
    """Rewrite repo-relative chapter links for MkDocs pages in docs/chapters/."""

    def repl_chapter(match: re.Match[str]) -> str:
        slug = match.group(1)
        return f"]({slug}.md)"

    text = re.sub(r"\]\(\.\./(\d{2}_[^)/]+)/?\)", repl_chapter, text)
    text = text.replace("../../docs/chapters.md", "../chapters.md")
    text = text.replace("../../docs/roadmap.md", "../roadmap.md")
    return text


def main() -> None:
    index = yaml.safe_load(INDEX.read_text(encoding="utf-8"))
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    nav_entries: list[dict[str, str]] = []
    chapter_ids = sorted(index["chapters"].keys(), key=lambda x: int(x))

    for cid in chapter_ids:
        meta = index["chapters"][cid]
        slug = meta["slug"]
        title = meta["title"]
        readme = ROOT / "chapters" / slug / "README.md"
        if not readme.exists():
            raise FileNotFoundError(readme)

        out_name = f"{slug}.md"
        out_path = OUT_DIR / out_name
        body = _rewrite_links(readme.read_text(encoding="utf-8"))
        out_path.write_text(
            f"<!-- generated by scripts/sync_chapter_docs.py — do not edit -->\n\n{body}",
            encoding="utf-8",
        )
        nav_entries.append({f"{cid} — {title}": f"chapters/{out_name}"})

    NAV_OUT.write_text(
        yaml.safe_dump(nav_entries, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )

    ASSETS_DST.mkdir(parents=True, exist_ok=True)
    copied = 0
    if ASSETS_SRC.is_dir():
        for gif in ASSETS_SRC.glob("*.gif"):
            shutil.copy2(gif, ASSETS_DST / gif.name)
            copied += 1

    print(f"Synced {len(nav_entries)} chapters to {OUT_DIR}")
    print(f"Copied {copied} GIF(s) to {ASSETS_DST}")
    print(f"Nav snippet: {NAV_OUT}")


if __name__ == "__main__":
    main()
